### ISSUE TITLE
[health 3.4.3] Headache Data

### ISSUE THREAD

**Issue by himalaya-08** [cph-cachet/flutter-plugins#497] opened 2022-02-04 12:27 UTC
Please define a data type for headache information on the Apple health kit.

**Comment by MadsVSChristensen** [comment] 2022-03-02 14:09
Duplicate of #498 

Hey @himalaya-08 

This has been completed and will be release with next version.

See https://github.com/cph-cachet/flutter-plugins/issues/498

Regards,
Mads

**Closed by MadsVSChristensen** 2022-03-02 14:09 UTC
Labels: duplicate issue
