### ISSUE TITLE
3.3.1

### ISSUE THREAD

**Issue by Pavi08** [cph-cachet/flutter-plugins#467] opened 2021-12-02 13:36 UTC
how  to  get the specify what permission is requested, e.g. READ ONLY, WRITE ONLY, READ_WRITE

**Comment by matsunanaro** [comment] 2021-12-03 07:38
Duplicate of #464

**Comment by Pavi08** [comment] 2021-12-04 03:55
How to het specify read permission only for health kit

**Comment by matsunanaro** [comment] 2021-12-05 14:55
I'm working on a fix that basically will, by default, request for read access only. Otherwise, the caller must explicitly request "write" or "read_write"

**Comment by bardram** [comment] 2021-12-29 20:32
This PR has been merged and published as version 3.4.0 of the plugin.

**Closed by bardram** 2021-12-29 20:32 UTC
Labels: bugfix
