### ISSUE TITLE
[health 2.0.6] - Permission bottom sheet not being triggered on physical device with iOS 14

### ISSUE THREAD

**Issue by annshsingh** [cph-cachet/flutter-plugins#207] opened 2020-10-12 08:12 UTC
**Experiencing this bug on:**
 - Device: iPhone 8
 - OS: iOS 14

**Bug Description:**
The default system generated permission bottom sheet is not triggered when asking for data from Apple Health. It was working fine on iOS 13. Maybe something changed with the way we access read permissions. Also, it works fine on Emulator with iOS 14 (iPhone 11 emulator).

**Steps to reproduce the behavior:**
Open the example app on physical device with iOS 14 and click on FAB.

**Expected behavior:**
Permission bottom sheet being triggered to ask for read access and then flow of data after that.

**Comment by thomasnilsson** [comment] 2020-10-18 21:18
I can't reproduce the error, I have tried on both the emulator and an iPhone XS - both running iOS 14, and they both work.

Could you attach some screenshots?

**Comment by annshsingh** [comment] 2020-10-19 08:04
@thomasnilsson Hey, thanks for getting back on this. 
I tried on another iPhone (iPhone 7) and it is working as expected. 
I then tried on iPhone 8 again, it started failing as before. I then tried on iPhone 11 pro which has the same apple account as iPhone 8 and it failed there as well.
As per my understanding, this could be **account specific** and not iOS or device specific. 
I am attaching the errors that I see on the console. 
Please see if you are able to understand what the issue might be.

Console logs for Health App example - 

`2020-10-19 13:14:42.444498+0530 Runner[1855:391364] [Assert] Connection request invalidated without resuming our _serviceSessionConnection. This is an error.
2020-10-19 13:14:42.445351+0530 Runner[1855:390784] [auth] Failed to get remote view controller: Error Domain=_UIViewServiceErrorDomain Code=1 "(null)" UserInfo={Canceled=service continuation}`

I then with the help of my colleague built a small app just to test Apple Health permission sheet and the results are same i.e. it works on iPhone 7 but failed on iPhone 8 and 11 pro (both of there share same apple account).
Console logs from a small native app just to test - 

`2020-10-19 13:25:03.451160+0530 HealthApp[1884:399150] [auth] FAILED prompting authorization request to share (
    HKWorkoutTypeIdentifier
), read (
    HKWorkoutTypeIdentifier
)
failure
Error Domain=com.apple.healthkit Code=100 "Authorization session timed out" UserInfo={NSLocalizedDescription=Authorization session timed out}
2020-10-19 13:25:03.461319+0530 HealthApp[1884:399149] [Assert] Connection request invalidated without resuming our _serviceSessionConnection. This is an error.
2020-10-19 13:25:03.461683+0530 HealthApp[1884:398627] [auth] Failed to get remote view controller: Error Domain=_UIViewServiceErrorDomain Code=1 "(null)" UserInfo={Canceled=service continuation}`

I hope this will help you pin point what the issue is. 
Would really appreciate your time on this issue. 
Thanks.

**Comment by thomasnilsson** [comment] 2020-10-24 16:20
So it is an issue specific to apple health? In this case we cannot do much unfortunately

**Comment by annshsingh** [comment] 2020-10-27 16:31
@thomasnilsson Not really sure on that actually. Might be related to something specific around permissions on the apple account. Can't say.

**Comment by thomasnilsson** [comment] 2020-11-07 13:50
I am gonna close the issue then. Feel free to create another one if you find out more 👍

**Closed by thomasnilsson** 2020-11-07 13:50 UTC
Labels: bugfix
