### ISSUE TITLE
[Health 3.4.3] Android Google Fit Login Access Denied

### ISSUE THREAD

**Issue by KuTaeHun** [cph-cachet/flutter-plugins#516] opened 2022-03-13 07:41 UTC
### Device / Emulator and OS
Please complete the following information for each phone and/or emulator you're experiencing this bug on:
 - Device: Samsung Galaxy S20, LG G8, Samsung Galaxy S21+
 - OS:  Andoird

### Describe the bug
I tested my app using a real Android phone. But randomly some user can not login the Google account. All of users who can't login the google account have more than two accounts. All of accounts can not access to the health data. I don't know why some test phone  can access the data and some cannot access...

### Flutter doctor 
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.2.1 21D62 darwin-arm, locale ko-KR)
    • Flutter version 2.10.3 at /Users/taehunku/developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (11 days ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/taehunku/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2)
    • Xcode at /Users/taehunku/Downloads/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.55.2)
    • VS Code at /Users/taehunku/Downloads/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.2.1 21D62 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 99.0.4844.51

[✓] HTTP Host Availability
    • All required HTTP hosts are available

### Additional information
There are another bug. This package cannot access step data. Some user's phone can access step data but some people who installed google fit can not access this.

**Comment by carsondu22** [comment] 2022-04-28 19:36
I had this same issue and found the cause.  After you created your OAuth client ID, it's necessary to whitelist the user accounts.  You need to go to the OAuth Consent Screen page to change the user type to allow the user accounts you want to use.  

<img width="491" alt="image" src="https://user-images.githubusercontent.com/7496604/165831927-33a15d50-81e9-4b07-a492-77589676acff.png">

**Comment by MadsVSChristensen** [comment] 2022-06-01 12:12
Hey @KuTaeHun 

Hopefully @carsondu22's answer helped you. We dont believe this is part of Health and I will therefore close this issue for now. Should you find that the problem was Health then please open a new issue!

Best Regards,
Mads

**Closed by MadsVSChristensen** 2022-06-01 12:12 UTC
Labels: bugfix
