### ISSUE TITLE
[Health 3.0.1+1] IOS Steps are fetched with incorrect value

### ISSUE THREAD

**Issue by mehraj-numen** [cph-cachet/flutter-plugins#440] opened 2021-10-27 05:23 UTC
[health 3.0.1+1]

### Device and OS
Device: [iPhone 7]
OS: [iOS 15]

### Describe the bug
The steps value are fetched incorrectly in most of the devices.
Observed behaviour: Getting incorrect values when user has mi-fit band and apple watch connected to health kit.

**Please compare the date values in  attached screen shots **
image 1: iPhone health kit screen shot.
image 2: My app screen shot.

![image_1](https://user-images.githubusercontent.com/69395424/139002697-1bf18ce7-90e9-44c0-9077-3478503d338e.png)

![image_2](https://user-images.githubusercontent.com/69395424/139002711-20ab4a13-2e23-4202-aa66-55b9322bc70d.png)

### To Reproduce
Just fetch the data from health api on iOS

### Expected behaviour
Getting same data count as showing in health kit.

### Actual behaviour
Health kit steps data and my app steps data values should be the same. 

### Flutter Doctor
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.3.1 20E241 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.5)
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.61.2)
[✓] Connected device

Thank you for any help you can offer.

**Comment by MadsVSChristensen** [comment] 2022-03-03 10:34
Hey @mehraj-numen 

I have tried to replicate this issue, but my values from the plug-in are correct and corresponds to the iOS values.

I will close this issue as it is for an older version of the plug-in and doesn't seem to be an issue anymore. If the issue is still present in the latest version, please create a new issue for that version. 

Regards,
Mads

**Closed by MadsVSChristensen** 2022-03-03 10:34 UTC
