### ISSUE TITLE
[Health 2.0.9] Screen flickers on Android when fetchData function is called

### ISSUE THREAD

**Issue by nikhilmufc7** [cph-cachet/flutter-plugins#233] opened 2020-11-20 07:42 UTC
### Device / Emulator and OS
Please complete the following information for each phone and/or emulator you're experiencing this bug on:
 - Device: Real Device (One Plus 7T)
 - OS: Android 10

### Describe the bug
Whenever the fetch data function is called the screen starts flickering in a weird way before it loads the data. This is happening only on Android on iOS it works perfectly as expected. 

### To Reproduce
Calling the fetch data function from the app , attaching a video which clearly depicts the issue

### Expected behavior
Its expected to not flicker and just show the loading spinner until the data loads

### Actual behavior
The screen starts flickering as in this video

![ezgif-7-e326aae06222](https://user-images.githubusercontent.com/20841184/99773100-ef1d5180-2b31-11eb-8a57-fcb853f41d69.gif)

### Flutter doctor 
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.2, on macOS 11.0.1 20B29, locale en-IN)

[✓] Android toolchain - develop for Android devices (Android SDK version
    29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.51.1)
[✓] Connected device (1 available)

• No issues found!```

**Comment by t-animal** [comment] 2020-11-23 13:08
This is a duplicate of #229

**Comment by thomasnilsson** [comment] 2020-11-29 22:14
Yes, #229 is the same issue as this. I have made good progress in this issue, but an update is not ready just yet.

**Comment by thomasnilsson** [comment] 2020-12-12 11:54
Check Health version 3.0.0 - the issue should now be fixed. 

Beware that you now have to request access manually before reading the data.

**Comment by nikhilmufc7** [comment] 2020-12-16 11:10
Thanks a lot , looks good in v3.0

**Closed** 2020-12-16 11:09 UTC
Labels: bugfix
