### ISSUE TITLE
Update graddle version in activity_recognition_flutter

### ISSUE THREAD

**Issue by bardram** [cph-cachet/flutter-plugins#76] opened 2020-04-30 19:48 UTC
**Plugin name & version**

activity_recognition_flutter

**Describe the bug**

When building to Android (Graddle), I get the following error message:

```
A problem occurred evaluating root project 'activity_recognition_flutter'.
> Failed to apply plugin [id 'com.android.internal.version-check']
   > Minimum supported Gradle version is 5.6.4. Current version is 5.4.1. If using the gradle wrapper, try editing the distributionUrl in /Users/bardram/.pub-cache/hosted/pub.dartlang.org/activity_recognition_flutter-1.0.3/android/gradle/wrapper/gradle-wrapper.properties to gradle-5.6.4-all.zip
```

It seems like the `build.graddle` file needs to be updated?

**To Reproduce**

Build the carp_mobile_sensing_app

**Smartphone(s) / Emulator**
Please complete the following information for each phone and/or emulator you're experiencing this bug on:

 - Device: Android, Samsung A3

**Comment by thomasnilsson** [comment] 2020-05-01 09:08
I am gonna try fixing this today

**Comment by thomasnilsson** [comment] 2020-05-01 10:37
Now it is working again. Going to close the issue.

I followed this [guide](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects), and it seems the easiest way to solve the problem is to upgrade the Android embedding API to v2 in the Carp Mobile Sensing App.

**Closed by thomasnilsson** 2020-05-01 10:37 UTC
Labels: bug
