### ISSUE TITLE
health: ^3.3.1

### ISSUE THREAD

**Issue by RiyaJaggi28** [cph-cachet/flutter-plugins#466] opened 2021-12-01 05:42 UTC
health

**Device / Emulator and OS**
 - Device: [iPhone 12 Simulator]
 - OS: [e.g. iOS 15.0]

**Describe the bug**
Crash when trying to access permission for EXERCISE_TIME.

**To Reproduce**
types = [
       HealthDataType.EXERCISE_TIME
      ];

 health.requestAuthorization(types)

**Expected behavior**
Asks user to grant permissions

**Actual behavior**
Crash with exception ‘Authorization to share the following types is disallowed: HKQuantityTypeIdentifierAppleExerciseTime’ 

@oakmad @ristiisa @Whathecode @drakmail @marinat

**Comment by matsunanaro** [comment] 2021-12-08 09:35
Duplicate of #464 

The crash was due to the implicit request for WRITE access.
PR #462 has been created to fix this one.

**Comment by bardram** [comment] 2021-12-29 20:31
This PR has been merged and published as version 3.4.0 of the plugin.

**Closed by bardram** 2021-12-29 20:31 UTC
Labels: bugfix
